version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/django"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "terraform"
    directory: "/terraform/gcp"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
